### ISSUE TITLE
mtnmomo.errors.ConfigurationError: ENVIRONMENT is missing in the configuration

### ISSUE THREAD

**Issue by umarfarukabu** [Mathewsmusukuma/lite-python-mtnmomo-api#4] opened 2021-11-13 18:46 UTC
Hello  am trying to integrate the momo API in my Django web app  but i keep getting this error even though i have set the Environment Variable in the config file. it says in your Readme that  it's optional to set the environment variable which when left blank it still raises the same exception : Here is what i did 
config = {  'ENVIRONMENT': os.environ.get("https://sandbox.momodeveloper.mtn.com/collection/v1_0/requesttopay"),
            'BASE_URL': os.environ.get("http://127.0.0.1:8000"),
            'CALLBACK_HOST': os.environ.get("http://127.0.0.1:8000"), }

mtnmomo.errors.ConfigurationError: ENVIRONMENT is missing in the configuration

**Comment by sikaili99** [comment] 2021-11-13 19:08
Hey, I think the issue is the setup you've used. Can you create a ```.env```  and update it with the variables that are in ```.env.example``` file? It should work . Don't edit ```config.py``` file

**Comment by sikaili99** [comment] 2021-12-01 07:16
@umarfarukabu did you manage to get past the configuration errors? Thank you

**Comment by sikaili99** [comment] 2022-07-18 08:51
I am closing this now. Thanks

**Closed as completed by sikaili99** 2022-07-18 08:51 UTC
